apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registries-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
